"""Initial multi-tenant schema

Revision ID: 5385246cb8d0
Revises: 
Create Date: 2026-02-01 13:11:12.525320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5385246cb8d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('token_quota_monthly', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('max_api_calls_per_day', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id_monthly', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id_yearly', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_billing_plans_active', 'billing_plans', ['is_active'], unique=False)
    op.create_index('idx_billing_plans_public', 'billing_plans', ['is_public'], unique=False)
    op.create_index(op.f('ix_billing_plans_created_at'), 'billing_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_plans_is_active'), 'billing_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_billing_plans_name'), 'billing_plans', ['name'], unique=True)
    op.create_index(op.f('ix_billing_plans_updated_at'), 'billing_plans', ['updated_at'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', 'TRIAL', name='tenantstatus'), nullable=False),
    sa.Column('plan_id', app.models.base.GUID(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('monthly_token_quota', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenants_slug', 'tenants', ['slug'], unique=False)
    op.create_index('idx_tenants_status', 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_deleted_at'), 'tenants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_tenants_updated_at'), 'tenants', ['updated_at'], unique=False)
    op.create_table('agent_tools',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('module_path', sa.String(length=500), nullable=False),
    sa.Column('parameters_schema', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_tools_active', 'agent_tools', ['is_active'], unique=False)
    op.create_index('idx_agent_tools_function', 'agent_tools', ['function_name'], unique=False)
    op.create_index('idx_agent_tools_tenant_name', 'agent_tools', ['tenant_id', 'name'], unique=True)
    op.create_index(op.f('ix_agent_tools_created_at'), 'agent_tools', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_tools_deleted_at'), 'agent_tools', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_tools_is_active'), 'agent_tools', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_tools_tenant_id'), 'agent_tools', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_tools_updated_at'), 'agent_tools', ['updated_at'], unique=False)
    op.create_table('providers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('OPENAI', 'ANTHROPIC', 'GEMINI', 'MISTRAL', 'AZURE_OPENAI', 'GROQ', 'OLLAMA', name='providertype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('credentials_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_health_status', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_providers_active', 'providers', ['is_active'], unique=False)
    op.create_index('idx_providers_default', 'providers', ['tenant_id', 'is_default'], unique=False)
    op.create_index('idx_providers_tenant_name', 'providers', ['tenant_id', 'name'], unique=True)
    op.create_index('idx_providers_type', 'providers', ['type'], unique=False)
    op.create_index(op.f('ix_providers_created_at'), 'providers', ['created_at'], unique=False)
    op.create_index(op.f('ix_providers_deleted_at'), 'providers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_providers_is_active'), 'providers', ['is_active'], unique=False)
    op.create_index(op.f('ix_providers_is_default'), 'providers', ['is_default'], unique=False)
    op.create_index(op.f('ix_providers_tenant_id'), 'providers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_providers_type'), 'providers', ['type'], unique=False)
    op.create_index(op.f('ix_providers_updated_at'), 'providers', ['updated_at'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roles_system', 'roles', ['is_system'], unique=False)
    op.create_index('idx_roles_tenant_name', 'roles', ['tenant_id', 'name'], unique=True)
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_roles_updated_at'), 'roles', ['updated_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('plan_id', app.models.base.GUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED', 'TRIAL', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('cancel_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('tokens_used_this_period', sa.Integer(), nullable=False),
    sa.Column('api_calls_today', sa.Integer(), nullable=False),
    sa.Column('last_usage_reset', sa.DateTime(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_metadata', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriptions_period', 'subscriptions', ['current_period_end'], unique=False)
    op.create_index('idx_subscriptions_plan', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_stripe', 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index('idx_subscriptions_tenant', 'subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_updated_at'), 'subscriptions', ['updated_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('user_id', app.models.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_keys_expires', 'api_keys', ['expires_at'], unique=False)
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_status', 'api_keys', ['status'], unique=False)
    op.create_index('idx_api_keys_tenant', 'api_keys', ['tenant_id'], unique=False)
    op.create_index('idx_api_keys_user', 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_deleted_at'), 'api_keys', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_status'), 'api_keys', ['status'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_keys_updated_at'), 'api_keys', ['updated_at'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', app.models.base.GUID(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_tenant', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('idx_audit_logs_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_updated_at'), 'audit_logs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('models',
    sa.Column('provider_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('supports_streaming', sa.Boolean(), nullable=False),
    sa.Column('supports_functions', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('cost_per_1k_input', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('cost_per_1k_output', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_metadata', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_models_active', 'models', ['is_active'], unique=False)
    op.create_index('idx_models_provider_name', 'models', ['provider_id', 'name'], unique=True)
    op.create_index(op.f('ix_models_created_at'), 'models', ['created_at'], unique=False)
    op.create_index(op.f('ix_models_is_active'), 'models', ['is_active'], unique=False)
    op.create_index(op.f('ix_models_provider_id'), 'models', ['provider_id'], unique=False)
    op.create_index(op.f('ix_models_updated_at'), 'models', ['updated_at'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('owner_id', app.models.base.GUID(), nullable=False),
    sa.Column('task_count', sa.Integer(), nullable=False),
    sa.Column('completed_task_count', sa.Integer(), nullable=False),
    sa.Column('project_metadata', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_owner', 'projects', ['owner_id'], unique=False)
    op.create_index('idx_projects_tenant_name', 'projects', ['tenant_id', 'name'], unique=False)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_projects_updated_at'), 'projects', ['updated_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('role_id', app.models.base.GUID(), nullable=False),
    sa.Column('assigned_by', app.models.base.GUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_roles_user_role', 'user_roles', ['user_id', 'role_id'], unique=True)
    op.create_index(op.f('ix_user_roles_created_at'), 'user_roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_updated_at'), 'user_roles', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('agents',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_id', app.models.base.GUID(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('top_p', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('frequency_penalty', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('presence_penalty', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('memory_strategy', sa.Enum('NONE', 'CONVERSATION_BUFFER', 'CONVERSATION_SUMMARY', 'VECTOR', name='memorystrategy'), nullable=False),
    sa.Column('memory_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agents_active', 'agents', ['is_active'], unique=False)
    op.create_index('idx_agents_model', 'agents', ['model_id'], unique=False)
    op.create_index('idx_agents_system', 'agents', ['is_system'], unique=False)
    op.create_index('idx_agents_tenant_name', 'agents', ['tenant_id', 'name'], unique=True)
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    op.create_index(op.f('ix_agents_deleted_at'), 'agents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agents_is_active'), 'agents', ['is_active'], unique=False)
    op.create_index(op.f('ix_agents_model_id'), 'agents', ['model_id'], unique=False)
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agents_updated_at'), 'agents', ['updated_at'], unique=False)
    op.create_table('agent_runs',
    sa.Column('agent_id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('session_id', app.models.base.GUID(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agentrunstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('run_metadata', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_runs_agent', 'agent_runs', ['agent_id'], unique=False)
    op.create_index('idx_agent_runs_created', 'agent_runs', ['created_at'], unique=False)
    op.create_index('idx_agent_runs_session', 'agent_runs', ['session_id'], unique=False)
    op.create_index('idx_agent_runs_status', 'agent_runs', ['status'], unique=False)
    op.create_index('idx_agent_runs_tenant_user_created', 'agent_runs', ['tenant_id', 'user_id', 'created_at'], unique=False)
    op.create_index('idx_agent_runs_user', 'agent_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_deleted_at'), 'agent_runs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_tenant_id'), 'agent_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_updated_at'), 'agent_runs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('agent_id', app.models.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='conversationstatus'), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_agent', 'conversations', ['agent_id'], unique=False)
    op.create_index('idx_conversations_status', 'conversations', ['status'], unique=False)
    op.create_index('idx_conversations_tenant_user', 'conversations', ['tenant_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('tenant_id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('agent_id', app.models.base.GUID(), nullable=True),
    sa.Column('provider_id', app.models.base.GUID(), nullable=True),
    sa.Column('model_id', app.models.base.GUID(), nullable=True),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('usage_metadata', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_logs_agent', 'usage_logs', ['agent_id'], unique=False)
    op.create_index('idx_usage_logs_analytics', 'usage_logs', ['tenant_id', 'user_id', 'operation_type', 'created_at'], unique=False)
    op.create_index('idx_usage_logs_billing', 'usage_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_usage_logs_created', 'usage_logs', ['created_at'], unique=False)
    op.create_index('idx_usage_logs_operation', 'usage_logs', ['operation_type'], unique=False)
    op.create_index('idx_usage_logs_tenant', 'usage_logs', ['tenant_id'], unique=False)
    op.create_index('idx_usage_logs_user', 'usage_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_agent_id'), 'usage_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_created_at'), 'usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_model_id'), 'usage_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_operation_type'), 'usage_logs', ['operation_type'], unique=False)
    op.create_index(op.f('ix_usage_logs_provider_id'), 'usage_logs', ['provider_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_tenant_id'), 'usage_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_updated_at'), 'usage_logs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', app.models.base.GUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'FUNCTION', 'TOOL', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('function_call', sa.JSON(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_messages_created', 'messages', ['created_at'], unique=False)
    op.create_index('idx_messages_role', 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_updated_at'), 'messages', ['updated_at'], unique=False)
    op.drop_index('idx_user_created', table_name='conversation_history')
    op.drop_index('idx_user_session', table_name='conversation_history')
    op.drop_index('ix_conversation_history_session_id', table_name='conversation_history')
    op.drop_index('ix_conversation_history_user_id', table_name='conversation_history')
    op.drop_table('conversation_history')
    op.drop_index('idx_audit_task_action', table_name='task_audit_log')
    op.drop_index('idx_audit_user_created', table_name='task_audit_log')
    op.drop_index('ix_task_audit_log_task_id', table_name='task_audit_log')
    op.drop_table('task_audit_log')
    op.drop_index('idx_user_expires', table_name='user_sessions')
    op.drop_index('ix_user_sessions_session_token', table_name='user_sessions')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.add_column('tasks', sa.Column('project_id', app.models.base.GUID(), nullable=True))
    op.add_column('tasks', sa.Column('created_by', app.models.base.GUID(), nullable=True))
    op.add_column('tasks', sa.Column('assigned_to', app.models.base.GUID(), nullable=True))
    op.add_column('tasks', sa.Column('task_metadata', sa.JSON(), nullable=False))
    op.add_column('tasks', sa.Column('tenant_id', app.models.base.GUID(), nullable=False))
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index('idx_user_id_due_date', table_name='tasks')
    op.drop_index('idx_user_id_priority', table_name='tasks')
    op.drop_index('idx_user_id_status', table_name='tasks')
    op.create_index('idx_tasks_assigned', 'tasks', ['assigned_to'], unique=False)
    op.create_index('idx_tasks_composite', 'tasks', ['tenant_id', 'user_id', 'status', 'priority'], unique=False)
    op.create_index('idx_tasks_project', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_tenant_due_date', 'tasks', ['tenant_id', 'due_date'], unique=False)
    op.create_index('idx_tasks_tenant_priority', 'tasks', ['tenant_id', 'priority'], unique=False)
    op.create_index('idx_tasks_tenant_status', 'tasks', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_tasks_tenant_user', 'tasks', ['tenant_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tasks_updated_at'), 'tasks', ['updated_at'], unique=False)
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('tenant_id', app.models.base.GUID(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_email', table_name='users')
    op.drop_index('idx_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index('idx_users_email_verified', 'users', ['email_verified'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('idx_users_tenant_email', 'users', ['tenant_id', 'email'], unique=True)
    op.create_index('idx_users_tenant_username', 'users', ['tenant_id', 'username'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('idx_users_tenant_username', table_name='users')
    op.drop_index('idx_users_tenant_email', table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_email_verified', table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_index('idx_username', 'users', ['username'], unique=False)
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'status')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_updated_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_index('idx_tasks_tenant_user', table_name='tasks')
    op.drop_index('idx_tasks_tenant_status', table_name='tasks')
    op.drop_index('idx_tasks_tenant_priority', table_name='tasks')
    op.drop_index('idx_tasks_tenant_due_date', table_name='tasks')
    op.drop_index('idx_tasks_project', table_name='tasks')
    op.drop_index('idx_tasks_composite', table_name='tasks')
    op.drop_index('idx_tasks_assigned', table_name='tasks')
    op.create_index('idx_user_id_status', 'tasks', ['user_id', 'status'], unique=False)
    op.create_index('idx_user_id_priority', 'tasks', ['user_id', 'priority'], unique=False)
    op.create_index('idx_user_id_due_date', 'tasks', ['user_id', 'due_date'], unique=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('tasks', 'tenant_id')
    op.drop_column('tasks', 'task_metadata')
    op.drop_column('tasks', 'assigned_to')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'project_id')
    op.create_table('user_sessions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('session_token', sa.VARCHAR(length=500), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_user_sessions_session_token', 'user_sessions', ['session_token'], unique=1)
    op.create_index('idx_user_expires', 'user_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('task_audit_log',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('task_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('action', sa.VARCHAR(length=9), nullable=False),
    sa.Column('old_values', sqlite.JSON(), nullable=True),
    sa.Column('new_values', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_audit_log_task_id', 'task_audit_log', ['task_id'], unique=False)
    op.create_index('idx_audit_user_created', 'task_audit_log', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_task_action', 'task_audit_log', ['task_id', 'action'], unique=False)
    op.create_table('conversation_history',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('session_id', sa.CHAR(length=36), nullable=False),
    sa.Column('role', sa.VARCHAR(length=9), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('intent', sa.VARCHAR(length=255), nullable=True),
    sa.Column('entities', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_history_user_id', 'conversation_history', ['user_id'], unique=False)
    op.create_index('ix_conversation_history_session_id', 'conversation_history', ['session_id'], unique=False)
    op.create_index('idx_user_session', 'conversation_history', ['user_id', 'session_id'], unique=False)
    op.create_index('idx_user_created', 'conversation_history', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_messages_updated_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_messages_role', table_name='messages')
    op.drop_index('idx_messages_created', table_name='messages')
    op.drop_index('idx_messages_conversation_created', table_name='messages')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_updated_at'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_tenant_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_provider_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_operation_type'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_model_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_created_at'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_agent_id'), table_name='usage_logs')
    op.drop_index('idx_usage_logs_user', table_name='usage_logs')
    op.drop_index('idx_usage_logs_tenant', table_name='usage_logs')
    op.drop_index('idx_usage_logs_operation', table_name='usage_logs')
    op.drop_index('idx_usage_logs_created', table_name='usage_logs')
    op.drop_index('idx_usage_logs_billing', table_name='usage_logs')
    op.drop_index('idx_usage_logs_analytics', table_name='usage_logs')
    op.drop_index('idx_usage_logs_agent', table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_index('idx_conversations_tenant_user', table_name='conversations')
    op.drop_index('idx_conversations_status', table_name='conversations')
    op.drop_index('idx_conversations_agent', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_updated_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_tenant_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_deleted_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_index('idx_agent_runs_user', table_name='agent_runs')
    op.drop_index('idx_agent_runs_tenant_user_created', table_name='agent_runs')
    op.drop_index('idx_agent_runs_status', table_name='agent_runs')
    op.drop_index('idx_agent_runs_session', table_name='agent_runs')
    op.drop_index('idx_agent_runs_created', table_name='agent_runs')
    op.drop_index('idx_agent_runs_agent', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agents_updated_at'), table_name='agents')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_model_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_is_active'), table_name='agents')
    op.drop_index(op.f('ix_agents_deleted_at'), table_name='agents')
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    op.drop_index('idx_agents_tenant_name', table_name='agents')
    op.drop_index('idx_agents_system', table_name='agents')
    op.drop_index('idx_agents_model', table_name='agents')
    op.drop_index('idx_agents_active', table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_updated_at'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_created_at'), table_name='user_roles')
    op.drop_index('idx_user_roles_user_role', table_name='user_roles')
    op.drop_index('idx_user_roles_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_projects_updated_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index('idx_projects_tenant_name', table_name='projects')
    op.drop_index('idx_projects_owner', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_models_updated_at'), table_name='models')
    op.drop_index(op.f('ix_models_provider_id'), table_name='models')
    op.drop_index(op.f('ix_models_is_active'), table_name='models')
    op.drop_index(op.f('ix_models_created_at'), table_name='models')
    op.drop_index('idx_models_provider_name', table_name='models')
    op.drop_index('idx_models_active', table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_updated_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user', table_name='audit_logs')
    op.drop_index('idx_audit_logs_tenant_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_tenant', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_updated_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_status'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_deleted_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_index('idx_api_keys_user', table_name='api_keys')
    op.drop_index('idx_api_keys_tenant', table_name='api_keys')
    op.drop_index('idx_api_keys_status', table_name='api_keys')
    op.drop_index('idx_api_keys_key_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_expires', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_subscriptions_updated_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_index('idx_subscriptions_tenant', table_name='subscriptions')
    op.drop_index('idx_subscriptions_stripe', table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_plan', table_name='subscriptions')
    op.drop_index('idx_subscriptions_period', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_roles_updated_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_index('idx_roles_tenant_name', table_name='roles')
    op.drop_index('idx_roles_system', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_providers_updated_at'), table_name='providers')
    op.drop_index(op.f('ix_providers_type'), table_name='providers')
    op.drop_index(op.f('ix_providers_tenant_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_is_default'), table_name='providers')
    op.drop_index(op.f('ix_providers_is_active'), table_name='providers')
    op.drop_index(op.f('ix_providers_deleted_at'), table_name='providers')
    op.drop_index(op.f('ix_providers_created_at'), table_name='providers')
    op.drop_index('idx_providers_type', table_name='providers')
    op.drop_index('idx_providers_tenant_name', table_name='providers')
    op.drop_index('idx_providers_default', table_name='providers')
    op.drop_index('idx_providers_active', table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_agent_tools_updated_at'), table_name='agent_tools')
    op.drop_index(op.f('ix_agent_tools_tenant_id'), table_name='agent_tools')
    op.drop_index(op.f('ix_agent_tools_is_active'), table_name='agent_tools')
    op.drop_index(op.f('ix_agent_tools_deleted_at'), table_name='agent_tools')
    op.drop_index(op.f('ix_agent_tools_created_at'), table_name='agent_tools')
    op.drop_index('idx_agent_tools_tenant_name', table_name='agent_tools')
    op.drop_index('idx_agent_tools_function', table_name='agent_tools')
    op.drop_index('idx_agent_tools_active', table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index(op.f('ix_tenants_updated_at'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_deleted_at'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_index('idx_tenants_status', table_name='tenants')
    op.drop_index('idx_tenants_slug', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_billing_plans_updated_at'), table_name='billing_plans')
    op.drop_index(op.f('ix_billing_plans_name'), table_name='billing_plans')
    op.drop_index(op.f('ix_billing_plans_is_active'), table_name='billing_plans')
    op.drop_index(op.f('ix_billing_plans_created_at'), table_name='billing_plans')
    op.drop_index('idx_billing_plans_public', table_name='billing_plans')
    op.drop_index('idx_billing_plans_active', table_name='billing_plans')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
